package btl_qlkhachhang;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import object.DonHang;
import object.DonHangTable;
import object.FileUtils;
import object.KhachHang;
import object.KhachHangTable;

public final class GiaoDien extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDien
     */
    ArrayList<KhachHang> dsKH = new ArrayList<>();
    ArrayList<DonHang> dsDH = new ArrayList<>();

    public GiaoDien() {
        initComponents();
        if (getData("khachhang.txt") != null) {
            dsKH = getData("khachhang.txt");
        }
        loadKHTable(dsKH);
        if (getData("donhang.txt") != null) {
            dsDH = getData("donhang.txt");
        }
        this.setTitle("Phần mềm quản lý ");
        loadDHTable(dsDH);
        txtTong.enable(false);
    }

    //Lấy ds trong file
    public ArrayList getData(String fileName) {
        ArrayList ds = new ArrayList<>();
        try {
            ds = FileUtils.docDanhSachTuFile(fileName);
            dsDH= FileUtils.docDanhSachTuFile(fileName);
        } catch (IOException | ClassNotFoundException e) {
//            JOptionPane.showMessageDialog(rootPane, e);
            JOptionPane.showMessageDialog(rootPane, "Không lấy được dữ liệu");
        }
        return ds;
    }

    public void loadKHTable(ArrayList list) {
        tbKhachHang.setModel(new KhachHangTable(list));
    }

    public void loadDHTable(ArrayList list) {
        tbDonHang.setModel(new DonHangTable(list));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        quanly = new javax.swing.JPanel();
        home = new javax.swing.JPanel();
        menu = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        list = new javax.swing.JPanel();
        KhachHang = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtTuoi = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        rdNam = new javax.swing.JRadioButton();
        rdNu = new javax.swing.JRadioButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnTim = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSapXep = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKhachHang = new javax.swing.JTable();
        btnTaoDon = new javax.swing.JButton();
        DonHang = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtMaThuoc = new javax.swing.JTextField();
        txtMaKhach = new javax.swing.JTextField();
        txtTenThuoc = new javax.swing.JTextField();
        txtTienThuoc = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnThemDon = new javax.swing.JButton();
        btnSuaDon = new javax.swing.JButton();
        btnXoaDon = new javax.swing.JButton();
        btnTimDon = new javax.swing.JButton();
        btnSapXepDon = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbDonHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnThongKe = new javax.swing.JButton();
        txtTong = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quanly.setLayout(new java.awt.CardLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("QUẢN LÝ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Quản lý khách hàng");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Quản lý đơn hàng");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Đăng xuất");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        list.setLayout(new java.awt.CardLayout());

        jLabel8.setText("Mã khách hàng");

        jLabel9.setText("Tên khách hàng");

        jLabel10.setText("Địa chỉ");

        jLabel11.setText("Tuổi");

        jLabel13.setText("Số điện thoại");

        jLabel14.setText("Giới tính");

        rdNam.setText("Nam");
        rdNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNamActionPerformed(evt);
            }
        });

        rdNu.setText("Nữ");
        rdNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdNuActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");

        btnTim.setText("Tìm");
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSapXep.setText("Sắp xếp");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });

        tbKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKhachHang);

        btnTaoDon.setText("Tạo đơn");
        btnTaoDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout KhachHangLayout = new javax.swing.GroupLayout(KhachHang);
        KhachHang.setLayout(KhachHangLayout);
        KhachHangLayout.setHorizontalGroup(
            KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhachHangLayout.createSequentialGroup()
                .addGroup(KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(KhachHangLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(31, 31, 31)
                        .addGroup(KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11))
                        .addGap(32, 32, 32)
                        .addGroup(KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(KhachHangLayout.createSequentialGroup()
                                .addComponent(rdNam)
                                .addGap(20, 20, 20)
                                .addComponent(rdNu))
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(KhachHangLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnThem)
                        .addGap(36, 36, 36)
                        .addComponent(btnSua)
                        .addGap(39, 39, 39)
                        .addComponent(btnTim)
                        .addGap(35, 35, 35)
                        .addComponent(btnXoa)
                        .addGap(31, 31, 31)
                        .addComponent(btnSapXep)
                        .addGap(32, 32, 32)
                        .addComponent(btnTaoDon)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(KhachHangLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        KhachHangLayout.setVerticalGroup(
            KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KhachHangLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(rdNam)
                    .addComponent(rdNu))
                .addGap(20, 20, 20)
                .addGroup(KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(60, 60, 60)
                .addGroup(KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnTim)
                    .addComponent(btnXoa)
                    .addComponent(btnSapXep)
                    .addComponent(btnTaoDon))
                .addContainerGap(227, Short.MAX_VALUE))
            .addGroup(KhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, KhachHangLayout.createSequentialGroup()
                    .addContainerGap(250, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        list.add(KhachHang, "card2");

        jLabel16.setText("Mã đơn thuốc");

        jLabel17.setText("Mã khách hàng");

        jLabel18.setText("Tên thuốc");

        jLabel19.setText("Giá tiền");

        jLabel20.setText("VND");

        btnThemDon.setText("Thêm");
        btnThemDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDonActionPerformed(evt);
            }
        });

        btnSuaDon.setText("Sửa");
        btnSuaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDonActionPerformed(evt);
            }
        });

        btnXoaDon.setText("Xóa");

        btnTimDon.setText("Tìm kiếm");
        btnTimDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimDonActionPerformed(evt);
            }
        });

        btnSapXepDon.setText("Sắp xếp");
        btnSapXepDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepDonActionPerformed(evt);
            }
        });

        tbDonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDonHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDonHangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbDonHang);

        jLabel1.setText("Tổng tiền");

        jLabel21.setText("VND");

        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DonHangLayout = new javax.swing.GroupLayout(DonHang);
        DonHang.setLayout(DonHangLayout);
        DonHangLayout.setHorizontalGroup(
            DonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DonHangLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(DonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(47, 47, 47)
                .addGroup(DonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaThuoc)
                    .addComponent(txtMaKhach)
                    .addComponent(txtTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(DonHangLayout.createSequentialGroup()
                        .addComponent(txtTienThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(15, 15, 15)
                .addGroup(DonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnThemDon)
                        .addComponent(btnSuaDon)
                        .addComponent(btnXoaDon))
                    .addGroup(DonHangLayout.createSequentialGroup()
                        .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel21)))
                .addGap(36, 36, 36)
                .addGroup(DonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThongKe)
                    .addComponent(btnSapXepDon)
                    .addComponent(btnTimDon))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(DonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DonHangLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        DonHangLayout.setVerticalGroup(
            DonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DonHangLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(DonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtMaThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemDon)
                    .addComponent(btnTimDon))
                .addGap(20, 20, 20)
                .addGroup(DonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtMaKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaDon)
                    .addComponent(btnSapXepDon))
                .addGap(19, 19, 19)
                .addGroup(DonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtTenThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaDon)
                    .addComponent(btnThongKe))
                .addGap(22, 22, 22)
                .addGroup(DonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtTienThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel1)
                    .addComponent(jLabel21)
                    .addComponent(txtTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(DonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DonHangLayout.createSequentialGroup()
                    .addGap(0, 210, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        list.add(DonHang, "card3");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(list, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        quanly.add(home, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quanly, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(quanly, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //
    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        KhachHang.setVisible(true);
        DonHang.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        KhachHang.setVisible(false);
        DonHang.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        login lg = new login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void btnTaoDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoDonActionPerformed
        // TODO add your handling code here:
        String MaKH = txtMaKH.getText();
        txtMaKhach.setText(MaKH);
        KhachHang.setVisible(false);
        DonHang.setVisible(true);
    }//GEN-LAST:event_btnTaoDonActionPerformed

    //thống kê số tiền trong đơn
    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        float tong = 0;
        for (DonHang dh : dsDH) {
            if (dh.getMakh().equals(txtMaKhach.getText())) {
                tong += dh.getTien();
            }
        }
        txtTong.setText(Float.toString(tong));
    }//GEN-LAST:event_btnThongKeActionPerformed

    //Thêm khách hàng
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        boolean boo = true;
        String mess = "";
        if ("".equals(txtMaKH.getText())) {
            mess = "Mã khách hàng không được để trống";
        } else if ("".equals(txtTenKH.getText())) {
            mess = "Tên khách hàng không được để trống";
        } else if ("".equals(txtDiaChi.getText())) {
            mess = "Địa chỉ không được để trống";
        } else if ("".equals(txtSDT.getText())) {
            mess = "Số điện thoại không được để trống";
        } else if ("".equals(txtTuoi.getText())) {
            mess = "Số tuổi không được để trống";
        } else if (rdNam.isSelected() == false && rdNu.isSelected() == false) {
            mess = "Chưa chọn giới tính";
        }

        if (!mess.equals("")) {
            JOptionPane.showMessageDialog(rootPane, mess);
        } else {
            for (KhachHang k : dsKH) {
                if (k.getMakh().equals(txtMaKH.getText())) {
                    boo = false;
                    break;
                }
            }
            if (boo) {
                KhachHang kh = new KhachHang();
                kh.setMakh(txtMaKH.getText());
                kh.setTenKh(txtTenKH.getText());
                kh.setDiaChi(txtDiaChi.getText());
                kh.setSoDt(txtSDT.getText());
                kh.setTuoi(Integer.parseInt(txtTuoi.getText()));
                kh.setMakh(txtMaKH.getText());
                if (rdNam.isSelected()) {
                    kh.setGioiTinh("Nam");
                }
                if (rdNu.isSelected()) {
                    kh.setGioiTinh("Nu");
                }
                dsKH.add(kh);
                try {
                    // Lưu danh sách đơn hàng vào file txt
                    FileUtils.ghiObjectVaoFile("khachhang.txt", dsKH);
                } catch (IOException e) {
                    System.out.println("khong luu dc file");
                }
                loadKHTable(dsKH);
                clearKH();
                JOptionPane.showMessageDialog(rootPane, "Thêm thành công");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Mã khách hàng đã tồn tại");
            }
        }


    }//GEN-LAST:event_btnThemActionPerformed

    private void rdNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNamActionPerformed
        // TODO add your handling code here:
        if (rdNam.isSelected()) {
            rdNu.setSelected(false);
        }
    }//GEN-LAST:event_rdNamActionPerformed

    private void rdNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdNuActionPerformed
        // TODO add your handling code here:
        if (rdNu.isSelected()) {
            rdNam.setSelected(false);
        }
    }//GEN-LAST:event_rdNuActionPerformed

    //Sắp xếp khách hàng theo tên
    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        // TODO add your handling code here:
        Collections.sort(dsKH);
        loadKHTable(dsKH);
//      JOptionPane.showMessageDialog(rootPane, "Sắp xếp");
    }//GEN-LAST:event_btnSapXepActionPerformed

    //Sửa dơn hàng
    private void btnSuaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDonActionPerformed
        // TODO add your handling code here:
        boolean boo = false;
        int d = -1;
        for (DonHang k : dsDH) {
            if (k.getMadh().equals(txtMaThuoc.getText())) {
                DonHang dh = new DonHang();
                dh.setMadh(txtMaThuoc.getText());
                dh.setMakh(txtMaKhach.getText());
                dh.setTenThuoc(txtTenThuoc.getText());
                dh.setTien(Float.parseFloat(txtTienThuoc.getText()));
                dsDH.set(d + 1, dh);
                try {
                    // Lưu danh sách đơn hàng vào file txt
                    FileUtils.ghiObjectVaoFile("donhang.txt", dsDH);
                } catch (IOException e) {
                    System.out.println("khong luu dc file");
                }
                loadDHTable(dsDH);
                clearDH();
                boo = true;
                break;
            } else {
                d++;
            }
        }
        if (!boo) {
            JOptionPane.showMessageDialog(rootPane, "Mã đơn không tồn tại, không thể sửa");
        }
    }//GEN-LAST:event_btnSuaDonActionPerformed

    //Thêm đơn hàng
    private void btnThemDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDonActionPerformed
        // TODO add your handling code here:
        boolean boo = true;
        String mess = "";
        if("".equals(txtMaThuoc.getText())) {
            mess = "Mã đơn hàng không được để trống";
        } else if("".equals(txtMaKhach.getText())) {
            mess = "Mã khách hàng không được để trống";
        } else if("".equals(txtTenThuoc.getText())) {
            mess = "Tên thuốc không được để trống";
        } else if("".equals(txtTenThuoc.getText())) {
            mess = "Số tiền không được để trống";
        }
        
        if(!mess.equals("")) {
            JOptionPane.showMessageDialog(rootPane, mess);
        } else {
            for(DonHang k : dsDH) {
                if (k.getMadh().equals(txtMaThuoc.getText())) {
                    boo = false;
                    break;
                }
            }
            if (boo) {
                DonHang dh = new DonHang();
                dh.setMadh(txtMaThuoc.getText());
                dh.setMakh(txtMaKhach.getText());
                dh.setTenThuoc(txtTenThuoc.getText());
                dh.setTien(Float.parseFloat(txtTienThuoc.getText()));
                dsDH.add(dh);
                try {
                    // Lưu danh sách đơn hàng vào file txt
                    FileUtils.ghiObjectVaoFile("donhang.txt", dsDH);
                } catch (IOException e) {
                    System.out.println("khong luu dc file");
                }
                loadDHTable(dsDH);
                clearDH();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Mã đơn đã tồn tại, không thể thêm");
            }
        }

    }//GEN-LAST:event_btnThemDonActionPerformed

    private void tbDonHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDonHangMouseClicked
        // TODO add your handling code here:
        int dong = tbDonHang.getSelectedRow();
        if (dong != -1) {
            DonHang dh = dsDH.get(dong);
            txtMaThuoc.setText(dh.getMadh() + "");
            txtMaKhach.setText(dh.getMakh() + "");
            txtTenThuoc.setText(dh.getTenThuoc());
            txtTienThuoc.setText(dh.getTien() + "");
        }
    }//GEN-LAST:event_tbDonHangMouseClicked

    private void tbKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhachHangMouseClicked
        // TODO add your handling code here:
        int dong = tbKhachHang.getSelectedRow();
        if (dong != -1) {
            KhachHang kh = dsKH.get(dong);
            txtMaKH.setText(kh.getMakh() + "");
            txtTenKH.setText(kh.getTenKh() + "");
            txtDiaChi.setText(kh.getDiaChi() + "");
            txtTuoi.setText(Integer.toString(kh.getTuoi()) + "");
            txtSDT.setText(kh.getSoDt() + "");
            if (kh.getGioiTinh().equals("Nam")) {
                rdNam.setSelected(true);
            } else {
                rdNu.setSelected(true);
            }

        }
    }//GEN-LAST:event_tbKhachHangMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int dong = tbKhachHang.getSelectedRow();
        if (dong != -1) {
            KhachHang kh = dsKH.get(dong);

            // Kiểm tra xem khách hàng có đơn hàng nào không
            boolean coDonHang = false;
            for (DonHang dh : dsDH) {
                if (dh.getMakh().equals(kh.getMakh())) {
                    coDonHang = true;
                    break;
                }
            }

            if (coDonHang) {
                JOptionPane.showMessageDialog(rootPane, "Không thể xóa khách hàng đã có đơn hàng!");
            } else {
                int luaChon = JOptionPane.showConfirmDialog(
                        rootPane,
                        "Bạn có chắc chắn muốn xóa khách hàng này?",
                        "Xác nhận xóa",
                        JOptionPane.YES_NO_OPTION
                );

                if (luaChon == JOptionPane.YES_OPTION) {
                    dsKH.remove(dong);

                    try {
                        FileUtils.ghiObjectVaoFile("khachhang.txt", dsKH);
                        loadKHTable(dsKH);
                        clearKH();
                        JOptionPane.showMessageDialog(rootPane, "Xóa thành công");
                    } catch (IOException e) {
                        JOptionPane.showMessageDialog(rootPane, "Xảy ra lỗi khi xóa dữ liệu");
                    }
                } 
            } 
        } else {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn khách hàng cần xóa!");
        }

    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnTimDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimDonActionPerformed
        // TODO add your handling code here:
        TimKiemDonHang tkdh = new TimKiemDonHang();
        tkdh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTimDonActionPerformed

    private void btnSapXepDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepDonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSapXepDonActionPerformed

    private void clearKH() {
        txtMaKH.setText("");
        txtTenKH.setText("");
        txtDiaChi.setText("");
        txtTuoi.setText("");
        txtSDT.setText("");
        rdNam.setSelected(false);
        rdNu.setSelected(false);
    }

    private void clearDH() {
        txtMaThuoc.setText("");
        txtMaKhach.setText("");
        txtTenThuoc.setText("");
        txtTienThuoc.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GiaoDien().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DonHang;
    private javax.swing.JPanel KhachHang;
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnSapXepDon;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSuaDon;
    private javax.swing.JButton btnTaoDon;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemDon;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnTimDon;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaDon;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel list;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel quanly;
    private javax.swing.JRadioButton rdNam;
    private javax.swing.JRadioButton rdNu;
    private javax.swing.JTable tbDonHang;
    private javax.swing.JTable tbKhachHang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaKhach;
    private javax.swing.JTextField txtMaThuoc;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTenThuoc;
    private javax.swing.JTextField txtTienThuoc;
    private javax.swing.JTextField txtTong;
    private javax.swing.JTextField txtTuoi;
    // End of variables declaration//GEN-END:variables
}
